apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: taskapp

resources:
  - namespace.yaml
  - configmap.yaml
  - taskapp-sealedsecret.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - migration/job.yaml
  - backend/service.yaml
  - backend/deployment.yaml
  - frontend/service.yaml
  - frontend/deployment.yaml
  - ingress/cluster-issuer.yaml
  - ingress/ingress.yaml