- name: Load Kubernetes kernel modules
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ kubernetes_kernel_modules }}"

- name: Persist Kubernetes kernel modules
  become: true
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k3s.conf
    owner: root
    group: root
    mode: "0644"
    content: |
      {% for module in kubernetes_kernel_modules %}
      {{ module }}
      {% endfor %}