- name: Disable SSH root login
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: "PermitRootLogin {{ ssh_permit_root_login }}"
    state: present
  notify: Restart ssh

- name: Disable SSH password authentication
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: "PasswordAuthentication {{ ssh_password_authentication }}"
    state: present
  notify: Restart ssh

- name: Enable SSH public key authentication
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: "PubkeyAuthentication {{ ssh_pubkey_authentication }}"
    state: present
  notify: Restart ssh