apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend
  namespace: taskapp
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: taskapp
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
