apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: taskapp
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: taskapp
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: frontend

  ports:
    - name: http
      port: 3000
      targetPort: 3000